# drift — CFN Drift Detective
# Usage: drift <stack-name> [--region <region>] [--profile <profile>] [--output <file>]
# Source this file from ~/.zshrc: source ~/.drift.zsh

drift() {
  # ── dependency check ──────────────────────────────────────────────────────
  if ! command -v jq &>/dev/null; then
    echo "[drift] error: jq is required (brew install jq)" >&2
    return 1
  fi
  if ! command -v aws &>/dev/null; then
    echo "[drift] error: aws CLI is required" >&2
    return 1
  fi

  # ── argument parsing ──────────────────────────────────────────────────────
  local STACK=""
  local REGION=""
  local PROFILE=""
  local OUTPUT_FILE=""
  local WRITE_FILE=false
  local -a AWS_ARGS=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --region)   REGION="$2";  shift 2 ;;
      --profile)  PROFILE="$2"; shift 2 ;;
      --out)      WRITE_FILE=true; shift ;;
      --output)   WRITE_FILE=true; OUTPUT_FILE="$2"; shift 2 ;;
      -*)
        echo "[drift] unknown flag: $1" >&2
        echo "Usage: drift <stack-name> [--region <region>] [--profile <profile>] [--out] [--output <file>]" >&2
        return 1
        ;;
      *)
        if [[ -z "$STACK" ]]; then
          STACK="$1"
        else
          echo "[drift] unexpected argument: $1" >&2
          return 1
        fi
        shift
        ;;
    esac
  done

  if [[ -z "$STACK" ]]; then
    echo "Usage: drift <stack-name> [--region <region>] [--profile <profile>] [--out] [--output <file>]" >&2
    return 1
  fi

  # strip template file extensions — allow passing alb-target-group.yaml directly
  local STACK_RAW="$STACK"
  STACK="${STACK%.yaml}"
  STACK="${STACK%.yml}"
  STACK="${STACK%.json}"
  STACK="${STACK%.template}"
  [[ "$STACK" != "$STACK_RAW" ]] && echo "[drift] treating '${STACK_RAW}' as stack name '${STACK}'"

  [[ -n "$REGION" ]]  && AWS_ARGS+=(--region  "$REGION")
  [[ -n "$PROFILE" ]] && AWS_ARGS+=(--profile "$PROFILE")

  local TIMESTAMP
  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
  if [[ "$WRITE_FILE" == true && -z "$OUTPUT_FILE" ]]; then
    OUTPUT_FILE="./drift-${STACK}-${TIMESTAMP}.md"
  fi

  local DISPLAY_REGION
  DISPLAY_REGION="${REGION:-${AWS_DEFAULT_REGION:-$(aws configure get region "${AWS_ARGS[@]}" 2>/dev/null || echo "default")}}"

  # ── initiate drift detection ──────────────────────────────────────────────
  local DETECTION_ID
  DETECTION_ID=$(aws cloudformation detect-stack-drift \
    --stack-name "$STACK" "${AWS_ARGS[@]}" \
    --query StackDriftDetectionId --output text 2>&1)

  if [[ $? -ne 0 ]]; then
    echo "[drift] failed to start detection:" >&2
    echo "  $DETECTION_ID" >&2
    return 1
  fi

  # ── poll until complete ───────────────────────────────────────────────────
  local STATUS=""
  local ELAPSED=0
  local STATUS_REASON=""

  printf "[drift] detecting %s" "$STACK"

  while true; do
    sleep 3
    ELAPSED=$((ELAPSED + 3))

    local POLL_JSON
    POLL_JSON=$(aws cloudformation describe-stack-drift-detection-status \
      --stack-drift-detection-id "$DETECTION_ID" "${AWS_ARGS[@]}" 2>&1)

    if [[ $? -ne 0 ]]; then
      printf "\n"
      echo "[drift] polling error: $POLL_JSON" >&2
      return 1
    fi

    STATUS=$(echo "$POLL_JSON" | jq -r '.DetectionStatus')
    printf "\r[drift] detecting %s ... %ds elapsed  " "$STACK" "$ELAPSED"

    if [[ "$STATUS" == "DETECTION_COMPLETE" || "$STATUS" == "DETECTION_FAILED" ]]; then
      printf "\n"
      break
    fi
  done

  if [[ "$STATUS" == "DETECTION_FAILED" ]]; then
    STATUS_REASON=$(echo "$POLL_JSON" | jq -r '.DetectionStatusReason // "unknown reason"')
    echo "[drift] detection failed: $STATUS_REASON" >&2
    return 1
  fi

  # ── fetch drift results ───────────────────────────────────────────────────
  local DRIFT_JSON
  DRIFT_JSON=$(aws cloudformation describe-stack-resource-drifts \
    --stack-name "$STACK" \
    --stack-resource-drift-status-filters MODIFIED DELETED \
    "${AWS_ARGS[@]}" 2>&1)

  if [[ $? -ne 0 ]]; then
    echo "[drift] failed to fetch drift results:" >&2
    echo "  $DRIFT_JSON" >&2
    return 1
  fi

  local DRIFT_COUNT
  DRIFT_COUNT=$(echo "$DRIFT_JSON" | jq '.StackResourceDrifts | length')

  # ── no-drift fast path ────────────────────────────────────────────────────
  if [[ "$DRIFT_COUNT" -eq 0 ]]; then
    echo "[drift] No drift detected. Stack ${STACK} is in sync."
    return 0
  fi

  # ── build markdown output ─────────────────────────────────────────────────
  local TS_HUMAN
  TS_HUMAN=$(date "+%Y-%m-%d %H:%M:%S")

  if [[ "$WRITE_FILE" == true ]]; then
  {
    # Header
    echo "# Drift Report: ${STACK}"
    echo ""
    echo "> Auto-generated by **drift** on ${TS_HUMAN}."
    echo "> Stack: \`${STACK}\` | Region: \`${DISPLAY_REGION}\`"
    echo ""

    # Summary table
    echo "## Summary"
    echo ""
    echo "${DRIFT_COUNT} resource(s) drifted."
    echo ""
    echo "| Logical ID | Type | Status |"
    echo "|---|---|---|"

    echo "$DRIFT_JSON" | jq -r '
      .StackResourceDrifts[] |
      "| `" + .LogicalResourceId + "` | " + .ResourceType + " | " + .StackResourceDriftStatus + " |"
    '

    echo ""

    # Per-resource deltas
    echo "## Resource Deltas"
    echo ""

    echo "$DRIFT_JSON" | jq -c '.StackResourceDrifts[]' | while IFS= read -r RESOURCE; do
      local LOGICAL_ID RESOURCE_TYPE DRIFT_STATUS
      LOGICAL_ID=$(echo "$RESOURCE" | jq -r '.LogicalResourceId')
      RESOURCE_TYPE=$(echo "$RESOURCE" | jq -r '.ResourceType')
      DRIFT_STATUS=$(echo "$RESOURCE" | jq -r '.StackResourceDriftStatus')

      echo "### \`${LOGICAL_ID}\` — ${RESOURCE_TYPE} — ${DRIFT_STATUS}"
      echo ""

      if [[ "$DRIFT_STATUS" == "DELETED" ]]; then
        echo "> This resource was **deleted** outside of CloudFormation."
        echo ""
      else
        local DIFF_COUNT
        DIFF_COUNT=$(echo "$RESOURCE" | jq '.PropertyDifferences | length')

        if [[ "$DIFF_COUNT" -gt 0 ]]; then
          echo "| Property | Expected (template) | Actual (live) | Change |"
          echo "|---|---|---|---|"

          echo "$RESOURCE" | jq -r '
            .PropertyDifferences[] |
            "| `" + .PropertyPath + "` | " +
            (.ExpectedValue // "*absent*") + " | " +
            (.ActualValue   // "*absent*") + " | " +
            .DifferenceType + " |"
          '
          echo ""
        fi
      fi
    done

    # Remediation section
    echo "## Remediation"
    echo ""

    echo "$DRIFT_JSON" | jq -c '.StackResourceDrifts[]' | while IFS= read -r RESOURCE; do
      local LOGICAL_ID RESOURCE_TYPE DRIFT_STATUS
      LOGICAL_ID=$(echo "$RESOURCE" | jq -r '.LogicalResourceId')
      RESOURCE_TYPE=$(echo "$RESOURCE" | jq -r '.ResourceType')
      DRIFT_STATUS=$(echo "$RESOURCE" | jq -r '.StackResourceDriftStatus')

      echo "### \`${LOGICAL_ID}\`"
      echo ""

      if [[ "$DRIFT_STATUS" == "DELETED" ]]; then
        echo "Resource was deleted outside CloudFormation. To restore, re-add to your template:"
        echo ""
        echo '```yaml'
        echo "# Re-add this resource block to your template and run a stack update."
        echo "${LOGICAL_ID}:"
        echo "  Type: ${RESOURCE_TYPE}"
        echo "  Properties:"
        echo "    # Restore from ExpectedProperties below or your source template."

        local EXPECTED_PROPS
        EXPECTED_PROPS=$(echo "$RESOURCE" | jq -r '.ExpectedProperties // "{}"')
        echo "$EXPECTED_PROPS" | jq -r 'to_entries[] | "    \(.key): \(.value | tostring)"' 2>/dev/null || true
        echo '```'
      else
        echo "To restore template state, update the live resource to match these expected properties:"
        echo ""
        echo '```yaml'
        echo "# Expected state (from CloudFormation template)"
        echo "${LOGICAL_ID}:"
        echo "  Type: ${RESOURCE_TYPE}"
        echo "  Properties:"

        local EXPECTED_PROPS
        EXPECTED_PROPS=$(echo "$RESOURCE" | jq -r '.ExpectedProperties // "{}"')
        echo "$EXPECTED_PROPS" | jq -r 'to_entries[] | "    \(.key): \(.value | tostring)"' 2>/dev/null || true
        echo '```'
      fi

      echo ""
      echo "**Verify after remediation:**"
      echo ""
      echo '```sh'
      local VERIFY_CMD="aws cloudformation detect-stack-drift --stack-name ${STACK}"
      [[ -n "$REGION" ]]  && VERIFY_CMD+=" --region ${REGION}"
      [[ -n "$PROFILE" ]] && VERIFY_CMD+=" --profile ${PROFILE}"
      echo "$VERIFY_CMD"
      echo '```'
      echo ""
    done

    # LLM context block
    echo "## LLM Context Block"
    echo ""
    echo "> Paste the block below into Claude or Copilot for remediation assistance."
    echo ""
    echo '```'
    echo "DRIFT CONTEXT"
    echo "============================================================"
    printf "Stack    : %s\n" "$STACK"
    printf "Region   : %s\n" "$DISPLAY_REGION"
    printf "Detected : %s\n" "$TS_HUMAN"
    printf "Drifted  : %d resource(s)\n" "$DRIFT_COUNT"
    echo ""

    echo "$DRIFT_JSON" | jq -c '.StackResourceDrifts[]' | while IFS= read -r RESOURCE; do
      local LOGICAL_ID RESOURCE_TYPE DRIFT_STATUS
      LOGICAL_ID=$(echo "$RESOURCE" | jq -r '.LogicalResourceId')
      RESOURCE_TYPE=$(echo "$RESOURCE" | jq -r '.ResourceType')
      DRIFT_STATUS=$(echo "$RESOURCE" | jq -r '.StackResourceDriftStatus')

      echo "--- ${LOGICAL_ID} (${RESOURCE_TYPE}) ---"
      echo "Status: ${DRIFT_STATUS}"

      if [[ "$DRIFT_STATUS" != "DELETED" ]]; then
        local DIFF_COUNT
        DIFF_COUNT=$(echo "$RESOURCE" | jq '.PropertyDifferences | length')
        if [[ "$DIFF_COUNT" -gt 0 ]]; then
          echo "Changes:"
          echo "$RESOURCE" | jq -r '
            .PropertyDifferences[] |
            "  " + .PropertyPath + ": expected=" +
            (.ExpectedValue // "absent") + " actual=" +
            (.ActualValue   // "absent")
          '
        fi
      else
        echo "Note: resource was deleted outside CloudFormation."
      fi
      echo ""
    done

    echo "Remediation goal: restore each resource's properties to the expected (template) values."
    echo "For DELETED resources: re-add the resource block to the template and run a stack update."
    echo '```'

  } > "$OUTPUT_FILE"
  fi

  # ── stdout summary ────────────────────────────────────────────────────────
  local RED='\033[0;31m'
  local GREEN='\033[0;32m'
  local YELLOW='\033[0;33m'
  local NC='\033[0m'

  echo "[drift] Detection complete — ${DRIFT_COUNT} resource(s) drifted in ${STACK}."

  while IFS= read -r RESOURCE; do
    local LID TYPE STATUS
    LID=$(echo "$RESOURCE"    | jq -r '.LogicalResourceId')
    TYPE=$(echo "$RESOURCE"   | jq -r '.ResourceType')
    STATUS=$(echo "$RESOURCE" | jq -r '.StackResourceDriftStatus')

    if [[ "$STATUS" == "DELETED" ]]; then
      printf "  • %s (%s) — ${RED}DELETED${NC} (removed outside CFN)\n" "$LID" "$TYPE"
    else
      local ADD_COUNT CHANGED_COUNT
      ADD_COUNT=$(    echo "$RESOURCE" | jq '[.PropertyDifferences[] | select(.DifferenceType == "ADD")]     | length')
      CHANGED_COUNT=$(echo "$RESOURCE" | jq '[.PropertyDifferences[] | select(.DifferenceType != "ADD")]     | length')

      if [[ "$CHANGED_COUNT" -gt 0 && "$ADD_COUNT" -gt 0 ]]; then
        printf "  • %s (%s) — ${YELLOW}%d changed${NC}, ${GREEN}%d added${NC}\n" \
          "$LID" "$TYPE" "$CHANGED_COUNT" "$ADD_COUNT"
      elif [[ "$CHANGED_COUNT" -gt 0 ]]; then
        printf "  • %s (%s) — ${YELLOW}%d property change(s)${NC}\n" "$LID" "$TYPE" "$CHANGED_COUNT"
      else
        printf "  • %s (%s) — ${GREEN}%d property addition(s)${NC}\n" "$LID" "$TYPE" "$ADD_COUNT"
      fi
    fi
  done < <(echo "$DRIFT_JSON" | jq -c '.StackResourceDrifts[]')

  [[ "$WRITE_FILE" == true ]] && printf "Report written to: %s\n" "$OUTPUT_FILE"
}
